name: Pages Preview

on:
  push:
    branches:
      - main  

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install  # Replace with your build commands, e.g., npm run build

      - name: Preview Pages site
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./  
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages 

